[build]
  # Directory to publish (the build output)
  publish = "dist"
  # Build command
  command = "npm run build"

# Environment variables
[build.environment]
  NODE_VERSION = "18"
  # Add any other environment variables here if needed
  # MY_ENV_VAR = "value"

# Handle SPA routing (React Router) - redirects to index.html so client-side routing works
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Performance and cache settings
[[headers]]
  # Define which paths get these headers
  for = "/*"
  [headers.values]
    # Cache control for static assets
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Different cache settings for HTML files
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Optimize asset handling
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Error page
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404 